baseURL = "https://novotnyr.github.io/"
languageCode = "en-us"
title = "robonovotny"

theme = "hugo-classic"

pygmentsCodeFences = true
pygmentsStyle = "murphy"

ignoreFiles = [ "___src" ]

[params]
  custom_css= [ "asciidoctor.css" ]

[markup]
  defaultMarkdownHandler = 'goldmark'

[security.exec]
    allow = ['asciidoctor']
